const types = {
    REQUEST_STATIONS: 'stationsReducer/REQUEST_STATIONS',
    REQUEST_STATIONS_ERROR: 'stationsReducer/REQUEST_STATIONS_ERROR',
    REQUEST_STATIONS_SUCCESS: 'stationsReducer/REQUEST_STATIONS_SUCCESS',
    ADD_STATION_TO_FAVORITES: 'stationsReducer/ADD_STATION_TO_FAVORITES',
    REMOVE_STATION_FROM_FAVORITES: 'stationsReducer/REMOVE_STATION_FROM_FAVORITES'
   }
   
   export default types   