const types = {
    REQUEST_NETWORKS: 'networkReducer/REQUEST_NETWORKS',
    REQUEST_NETWORKS_ERROR: 'networkReducer/REQUEST_NETWORKS_ERROR',
    REQUEST_NETWORKS_SUCCESS: 'networkReducer/REQUEST_NETWORKS_SUCCESS',
    SET_NETWORK_ACTIVE: 'networkReducer/SET_NETWORK_ACTIVE',
    ADD_NETWORK_TO_FAVORITES: 'networkReducer/ADD_NETWORK_TO_FAVORITES',
    REMOVE_NETWORK_FROM_FAVORITES: 'networkReducer/REMOVE_NETWORK_FROM_FAVORITES'
}

export default types   